// Curated ayahs for each mood
// Each entry: { surah, ayah, theme } — fetched live from the API

export const MOODS = [
  {
    id: "sad",
    label: "Sad",
    emoji: "😔",
    color: "#6b7db3",
    lightBg: "rgba(107,125,179,0.08)",
    border: "rgba(107,125,179,0.3)",
    description: "Find comfort in Allah's words",
  },
  {
    id: "happy",
    label: "Happy",
    emoji: "😊",
    color: "#c4892e",
    lightBg: "rgba(196,137,46,0.08)",
    border: "rgba(196,137,46,0.3)",
    description: "Express gratitude and joy",
  },
  {
    id: "lonely",
    label: "Lonely",
    emoji: "🌙",
    color: "#7c6fa0",
    lightBg: "rgba(124,111,160,0.08)",
    border: "rgba(124,111,160,0.3)",
    description: "Remember Allah is always near",
  },
  {
    id: "anxious",
    label: "Anxious",
    emoji: "😰",
    color: "#5a9e8f",
    lightBg: "rgba(90,158,143,0.08)",
    border: "rgba(90,158,143,0.3)",
    description: "Find peace and stillness",
  },
  {
    id: "notwell",
    label: "Not Feeling Well",
    emoji: "🤲",
    color: "#b06060",
    lightBg: "rgba(176,96,96,0.08)",
    border: "rgba(176,96,96,0.3)",
    description: "Seek healing and strength",
  },
];

export const MOOD_AYAHS = {
  sad: [
    { surah: 94, ayah: 5,  theme: "After hardship comes ease" },
    { surah: 94, ayah: 6,  theme: "Ease follows every difficulty" },
    { surah: 2,  ayah: 286, theme: "Allah does not burden a soul beyond that it can bear" },
    { surah: 3,  ayah: 139, theme: "Do not lose hope" },
    { surah: 39, ayah: 53, theme: "Do not despair of Allah's mercy" },
    { surah: 93, ayah: 3,  theme: "Your Lord has not forsaken you" },
    { surah: 93, ayah: 4,  theme: "The hereafter is better for you" },
    { surah: 2,  ayah: 155, theme: "Allah is with the patient" },
    { surah: 2,  ayah: 156, theme: "We belong to Allah and to Him we return" },
    { surah: 13, ayah: 28, theme: "Hearts find rest in remembrance of Allah" },
    { surah: 65, ayah: 3,  theme: "Allah is sufficient for those who trust in Him" },
    { surah: 94, ayah: 1,  theme: "Did We not expand your chest" },
    { surah: 12, ayah: 87, theme: "Never give up hope of Allah's mercy" },
    { surah: 3,  ayah: 173, theme: "Allah is sufficient for us" },
    { surah: 9,  ayah: 40, theme: "Allah is with us" },
  ],
  happy: [
    { surah: 1,  ayah: 2,  theme: "All praise be to Allah" },
    { surah: 14, ayah: 7,  theme: "If you are grateful, I will give you more" },
    { surah: 55, ayah: 13, theme: "Which of the favors of your Lord would you deny?" },
    { surah: 16, ayah: 18, theme: "You cannot count Allah's blessings" },
    { surah: 93, ayah: 11, theme: "Speak about the blessings of your Lord" },
    { surah: 2,  ayah: 152, theme: "Remember Me and I will remember you" },
    { surah: 31, ayah: 12, theme: "Whoever is grateful, it is for himself" },
    { surah: 27, ayah: 19, theme: "Grant me gratitude for Your blessings" },
    { surah: 10, ayah: 58, theme: "Rejoice in the mercy of Allah" },
    { surah: 3,  ayah: 171, theme: "They rejoice in the favor of Allah" },
    { surah: 55, ayah: 60, theme: "Is the reward of goodness but goodness?" },
    { surah: 16, ayah: 114, theme: "Be grateful for Allah's blessings" },
  ],
  lonely: [
    { surah: 2,  ayah: 186, theme: "Allah is near and responds to the caller" },
    { surah: 50, ayah: 16, theme: "Allah is closer to you than your jugular vein" },
    { surah: 9,  ayah: 40, theme: "Allah is with us" },
    { surah: 13, ayah: 28, theme: "Hearts find rest in Allah's remembrance" },
    { surah: 57, ayah: 4,  theme: "He is with you wherever you are" },
    { surah: 58, ayah: 7,  theme: "Allah is with them wherever they are" },
    { surah: 93, ayah: 3,  theme: "Your Lord has not forsaken you" },
    { surah: 20, ayah: 46, theme: "I am with you, hearing and seeing" },
    { surah: 8,  ayah: 46, theme: "Allah is with the patient" },
    { surah: 3,  ayah: 68, theme: "Allah is the protector of the believers" },
    { surah: 6,  ayah: 17, theme: "He is the Aware, the Acquainted" },
    { surah: 40, ayah: 60, theme: "Call upon Me and I will respond" },
  ],
  anxious: [
    { surah: 3,  ayah: 173, theme: "Allah is sufficient for us" },
    { surah: 8,  ayah: 2,  theme: "When Allah is mentioned, hearts tremble with awe" },
    { surah: 16, ayah: 128, theme: "Allah is with those who fear Him" },
    { surah: 2,  ayah: 45, theme: "Seek help through patience and prayer" },
    { surah: 65, ayah: 3,  theme: "Whoever trusts in Allah, He is sufficient" },
    { surah: 13, ayah: 28, theme: "Hearts find rest in remembrance of Allah" },
    { surah: 4,  ayah: 147, theme: "What would Allah do with your punishment?" },
    { surah: 33, ayah: 3,  theme: "Put your trust in Allah" },
    { surah: 25, ayah: 58, theme: "Trust in the Ever-Living who does not die" },
    { surah: 39, ayah: 36, theme: "Is Allah not sufficient for His servant?" },
    { surah: 3,  ayah: 160, theme: "If Allah helps you, none can overcome you" },
    { surah: 9,  ayah: 51, theme: "Nothing will happen to us except what Allah decrees" },
    { surah: 33, ayah: 48, theme: "Put your trust in Allah" },
  ],
  notwell: [
    { surah: 26, ayah: 80, theme: "When I am ill, He heals me" },
    { surah: 10, ayah: 57, theme: "A healing for what is in the hearts" },
    { surah: 17, ayah: 82, theme: "The Quran is healing and mercy" },
    { surah: 41, ayah: 44, theme: "A guide and healing for the believers" },
    { surah: 3,  ayah: 173, theme: "Allah is sufficient for us" },
    { surah: 2,  ayah: 286, theme: "Allah does not burden beyond capacity" },
    { surah: 94, ayah: 5,  theme: "With hardship comes ease" },
    { surah: 39, ayah: 53, theme: "Do not despair of Allah's mercy" },
    { surah: 2,  ayah: 155, theme: "Allah is with the patient" },
    { surah: 21, ayah: 83, theme: "Adversity has touched me and You are merciful" },
    { surah: 21, ayah: 84, theme: "We responded to him and removed his adversity" },
    { surah: 6,  ayah: 17, theme: "If Allah touches you with harm, none can remove it but Him" },
    { surah: 16, ayah: 128, theme: "Allah is with those who are patient" },
  ],
};