// Rich metadata for all 114 surahs
// Used by the comparison feature

export const SURAH_META = {
  1:   { themes: ["Prayer","Guidance","Worship"],          topics: ["Opening supplication","Path of the righteous","Seven oft-repeated verses"],      keyVerse: "1:6",  color: "#c4892e" },
  2:   { themes: ["Law","Faith","Community"],               topics: ["Longest surah","Ayat al-Kursi","Rules of fasting, hajj, marriage"],             keyVerse: "2:255", color: "#7c6fa0" },
  3:   { themes: ["Faith","Family of Imran","Unity"],       topics: ["Battle of Uhud","Jesus and Mary","Importance of steadfastness"],                 keyVerse: "3:139", color: "#5a9e8f" },
  4:   { themes: ["Justice","Women's Rights","Inheritance"],topics: ["Rights of women","Inheritance law","Treatment of orphans"],                      keyVerse: "4:1",   color: "#b06060" },
  5:   { themes: ["Covenant","Food Law","Justice"],          topics: ["Halal food rules","Jesus's miracles","Prohibition of intoxicants"],              keyVerse: "5:3",   color: "#6b7db3" },
  6:   { themes: ["Tawheed","Prophethood","Reasoning"],     topics: ["Abraham's monotheism","Signs in creation","Against polytheism"],                  keyVerse: "6:103", color: "#c4892e" },
  7:   { themes: ["History","Prophets","Accountability"],   topics: ["Adam and Iblis","Stories of Nuh, Hud, Salih","Day of Judgment"],                  keyVerse: "7:56",  color: "#7c6fa0" },
  8:   { themes: ["Jihad","Spoils of War","Trust in Allah"],topics: ["Battle of Badr","Distribution of war spoils","Importance of obedience"],          keyVerse: "8:2",   color: "#5a9e8f" },
  9:   { themes: ["Disavowal","Hypocrites","Repentance"],   topics: ["Treaty cancellation","Expose of hypocrites","Jizyah"],                           keyVerse: "9:128", color: "#b06060" },
  10:  { themes: ["Signs","Prophethood","Patience"],         topics: ["Story of Yunus","Signs in creation","Warnings to disbelievers"],                  keyVerse: "10:57", color: "#6b7db3" },
  11:  { themes: ["Prophets","Punishment","Steadfastness"],  topics: ["Story of Nuh, Hud, Salih, Lut","Divine punishment","Mercy for believers"],       keyVerse: "11:6",  color: "#c4892e" },
  12:  { themes: ["Patience","Trust","Providence"],          topics: ["Complete story of Yusuf","Patience in adversity","Allah's plan"],                 keyVerse: "12:87", color: "#7c6fa0" },
  13:  { themes: ["Thunder","Signs","Guidance"],             topics: ["Signs in creation","Attributes of Allah","Quran as guidance"],                   keyVerse: "13:28", color: "#5a9e8f" },
  14:  { themes: ["Gratitude","Tawheed","Prayer of Ibrahim"],topics: ["Ibrahim's prayer","Parable of good and evil word","Blessings and ingratitude"],  keyVerse: "14:7",  color: "#b06060" },
  15:  { themes: ["Quran's Protection","Prophets","Hell"],   topics: ["Gardens of Paradise","Story of Iblis","Protection of Quran"],                    keyVerse: "15:9",  color: "#6b7db3" },
  16:  { themes: ["Blessings","Honey Bee","Guidance"],       topics: ["Countless blessings of Allah","Honey bee miracle","Halal and haram"],             keyVerse: "16:128",color: "#c4892e" },
  17:  { themes: ["Night Journey","Bani Israel","Ethics"],   topics: ["Isra wal Miraj","Ten commandments","Rights of parents"],                          keyVerse: "17:23", color: "#7c6fa0" },
  18:  { themes: ["Trial","Knowledge","Time"],               topics: ["People of the Cave","Dhul-Qarnayn","Khidr and Musa"],                             keyVerse: "18:110",color: "#5a9e8f" },
  19:  { themes: ["Mercy","Mary","Prophets"],                topics: ["Birth of Isa","Yahya's story","Ibrahim and his father"],                          keyVerse: "19:96", color: "#b06060" },
  20:  { themes: ["Musa","Patience","Quran"],                topics: ["Musa and Pharaoh","Story of the golden calf","Forgiveness"],                      keyVerse: "20:14", color: "#6b7db3" },
  36:  { themes: ["Heart of Quran","Resurrection","Signs"],  topics: ["Proof of resurrection","Signs in nature","Stories of messengers"],                keyVerse: "36:12", color: "#c4892e" },
  55:  { themes: ["Mercy","Blessings","Accountability"],     topics: ["78 blessings of Allah","Balance and justice","Jinn and humans"],                  keyVerse: "55:13", color: "#7c6fa0" },
  56:  { themes: ["Resurrection","Three Groups","Jannah"],   topics: ["The foremost, companions of right, left","Jannah's descriptions","Kufr warning"], keyVerse: "56:77", color: "#5a9e8f" },
  57:  { themes: ["Charity","Munafiqeen","Light"],            topics: ["Importance of sadaqah","Hypocrites exposed","World as play"],                     keyVerse: "57:3",  color: "#b06060" },
  67:  { themes: ["Dominion","Creation","Warning"],           topics: ["Seven heavens","Signs of Allah's power","Warning of punishment"],                 keyVerse: "67:2",  color: "#6b7db3" },
  68:  { themes: ["Quran","Character","Patience"],            topics: ["Prophet's noble character","Story of garden owners","Patience"],                  keyVerse: "68:4",  color: "#c4892e" },
  78:  { themes: ["Resurrection","Day of Judgment","Hell"],  topics: ["Signs of Allah's power","Detailed description of Judgment Day","Jannah"],         keyVerse: "78:1",  color: "#7c6fa0" },
  84:  { themes: ["Accountability","Splitting","Sky"],        topics: ["Sky splitting","Earth spreading","Everyone will face their record"],               keyVerse: "84:6",  color: "#5a9e8f" },
  87:  { themes: ["Purification","Quran","Ease"],             topics: ["Glorify Allah's name","Quran will be remembered","Hereafter is better"],          keyVerse: "87:7",  color: "#b06060" },
  89:  { themes: ["Dawn","Ancient Nations","Soul"],           topics: ["Aad and Thamud","Human ingratitude","Satisfied soul"],                            keyVerse: "89:27", color: "#6b7db3" },
  93:  { themes: ["Comfort","Orphan","Gratitude"],            topics: ["Allah did not forsake the Prophet","Orphan's rights","Blessings"],                 keyVerse: "93:5",  color: "#c4892e" },
  94:  { themes: ["Relief","Hardship","Ease"],                topics: ["Expansion of chest","Ease after hardship","Gratitude in worship"],                keyVerse: "94:5",  color: "#7c6fa0" },
  95:  { themes: ["Creation","Accountability","Religion"],    topics: ["Best creation","Lowest of low","Judgment Day"],                                   keyVerse: "95:4",  color: "#5a9e8f" },
  96:  { themes: ["First Revelation","Knowledge","Creation"], topics: ["Read in the name of Allah","Pen and knowledge","Human arrogance"],                keyVerse: "96:1",  color: "#b06060" },
  99:  { themes: ["Earthquake","Accountability","Deeds"],     topics: ["Earth's convulsion","People scattered","Atoms worth of deeds"],                   keyVerse: "99:7",  color: "#6b7db3" },
  108: { themes: ["Abundance","Prayer","Sacrifice"],           topics: ["Al-Kawthar river","Prayer and sacrifice","Enemies cut off"],                      keyVerse: "108:1", color: "#c4892e" },
  109: { themes: ["Disbelief","Monotheism","Rejection"],       topics: ["Clear rejection of polytheism","To you your religion","Tolerance"],               keyVerse: "109:6", color: "#7c6fa0" },
  110: { themes: ["Victory","Islam","Forgiveness"],            topics: ["Help of Allah","People entering Islam","Praise and forgiveness"],                 keyVerse: "110:3", color: "#5a9e8f" },
  112: { themes: ["Tawheed","Sincerity","Allah's Nature"],     topics: ["Allah is One","Allah the Eternal Refuge","No partners"],                          keyVerse: "112:1", color: "#b06060" },
  113: { themes: ["Refuge","Evil","Darkness"],                 topics: ["Refuge from darkness","Envy","Evil of what He created"],                          keyVerse: "113:1", color: "#6b7db3" },
  114: { themes: ["Refuge","Whispers","Humans and Jinn"],      topics: ["Refuge from whisperer","Who whispers in hearts","Jinn and humans"],               keyVerse: "114:1", color: "#c4892e" },
};

// Default metadata for surahs not in the detailed list
export function getSurahMeta(number) {
  return SURAH_META[number] || {
    themes: ["Faith", "Guidance", "Worship"],
    topics: [`Surah ${number}`, "Quranic guidance", "Divine wisdom"],
    keyVerse: `${number}:1`,
    color: "#c4892e",
  };
}

export const SURAH_NAMES = {
  1:"Al-Fatihah",2:"Al-Baqarah",3:"Aal-Imran",4:"An-Nisa",5:"Al-Maidah",
  6:"Al-Anam",7:"Al-Araf",8:"Al-Anfal",9:"At-Tawbah",10:"Yunus",
  11:"Hud",12:"Yusuf",13:"Ar-Rad",14:"Ibrahim",15:"Al-Hijr",
  16:"An-Nahl",17:"Al-Isra",18:"Al-Kahf",19:"Maryam",20:"Ta-Ha",
  21:"Al-Anbiya",22:"Al-Hajj",23:"Al-Muminun",24:"An-Nur",25:"Al-Furqan",
  26:"Ash-Shuara",27:"An-Naml",28:"Al-Qasas",29:"Al-Ankabut",30:"Ar-Rum",
  31:"Luqman",32:"As-Sajdah",33:"Al-Ahzab",34:"Saba",35:"Fatir",
  36:"Ya-Sin",37:"As-Saffat",38:"Sad",39:"Az-Zumar",40:"Ghafir",
  41:"Fussilat",42:"Ash-Shura",43:"Az-Zukhruf",44:"Ad-Dukhan",45:"Al-Jathiyah",
  46:"Al-Ahqaf",47:"Muhammad",48:"Al-Fath",49:"Al-Hujurat",50:"Qaf",
  51:"Adh-Dhariyat",52:"At-Tur",53:"An-Najm",54:"Al-Qamar",55:"Ar-Rahman",
  56:"Al-Waqiah",57:"Al-Hadid",58:"Al-Mujadila",59:"Al-Hashr",60:"Al-Mumtahanah",
  61:"As-Saf",62:"Al-Jumuah",63:"Al-Munafiqun",64:"At-Taghabun",65:"At-Talaq",
  66:"At-Tahrim",67:"Al-Mulk",68:"Al-Qalam",69:"Al-Haqqah",70:"Al-Maarij",
  71:"Nuh",72:"Al-Jinn",73:"Al-Muzzammil",74:"Al-Muddaththir",75:"Al-Qiyamah",
  76:"Al-Insan",77:"Al-Mursalat",78:"An-Naba",79:"An-Naziat",80:"Abasa",
  81:"At-Takwir",82:"Al-Infitar",83:"Al-Mutaffifin",84:"Al-Inshiqaq",85:"Al-Buruj",
  86:"At-Tariq",87:"Al-Ala",88:"Al-Ghashiyah",89:"Al-Fajr",90:"Al-Balad",
  91:"Ash-Shams",92:"Al-Layl",93:"Ad-Duha",94:"Ash-Sharh",95:"At-Tin",
  96:"Al-Alaq",97:"Al-Qadr",98:"Al-Bayyinah",99:"Az-Zalzalah",100:"Al-Adiyat",
  101:"Al-Qariah",102:"At-Takathur",103:"Al-Asr",104:"Al-Humazah",105:"Al-Fil",
  106:"Quraysh",107:"Al-Maun",108:"Al-Kawthar",109:"Al-Kafirun",110:"An-Nasr",
  111:"Al-Masad",112:"Al-Ikhlas",113:"Al-Falaq",114:"An-Nas",
};